import { useEffect } from 'react'
import { useRouter } from "next/router"
import Head from 'next/head'

export default function Home() {
  const router = useRouter()

  useEffect(() => {
    router.push("/feedback")
  },[])
  return (
    <>
      <Head>
        <title>FeedBack Portal - W-DRIVE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       
      </main>
    </>
  )
}
